
text = """
Ele acordou. Havia cochilado sentado na taverna. Depois de tantos dias de trabalho intenso, sentar perto de um fogo com a barriga cheia derruba qualquer um, mesmo com a música e o som de conversa constante em qualquer taverna. Olhou ao redor, tentando descobrir por quanto tempo dormiu, mas sem muito sucesso. O ambiente ali dentro parecia uniforme, o ritmo não se alterava e os rostos se confundiam com a iluminação, de modo que não tinha como saber se dormira pouco ou muito. Porém, a julgar por seus pensamentos lentos e a leve dor de cabeça, julgava ter sido bastante. 
'Nada como pegar no sono sentado', pensou, enquanto pedia uma caneca de café. Essa taverna era conhecida na cidade por ter os melhores cafés e, além disso, o clima estava especialmente convidativo. Apesar de estar aquecido, ao olhar pela janela e ver as pessoas passando, o vento soprando roupas e papéis, a luminosidade cinzenta do dia, podia praticamente sentir em sua espinha o frio lá de fora. 
Enquanto refletia sobre isso, seu café chegou. Um bom café preto aromatizado naturalmente com castanhas, acompanhado de uma fatia de bolo, “cortesia da casa”, ouviu a atendente dizer, enquanto já se afastava e sua voz se perdia no ruído da sala. O inebriante cheiro de café logo chegou a suas narinas e seu corpo foi invadido por uma onda de prazer. Tomou um gole e permitiu que seus pensamentos vagassem… parecia a coisa apropriada a fazer nesse momento. 
'Até que a vida não é tão ruim', foi a primeira coisa que passou pela sua cabeça. Era certo que ele estava exausto de seu trabalho e que diversas vezes pensava em desistir de tudo e fugir. Nunca, é claro, colocou esses pensamentos em prática, mas eles eram uma constante em sua vida. Apesar disso, há um mistério, um prazer sussurrante na vida. Apesar de momentos de desânimo, como desistir de tudo agora? Agora que já havia feito tanto e pago tão caro para chegar aonde estava. Agora que sua família estava em feliz. Agora que tantas pessoas olhavam para ele e esperavam tanto. 'Ah, como é bom esse momento de solidão no qual ninguém sabe quem sou nem espera nada de mim', foi sua reação instantânea. 
Isso não é tudo, é claro. Havia momentos como esse, onde ele se sentia genuinamente feliz com coisas banais, como tomar um bom café e ganhar um pedaço de bolo. Havia momentos em que se encontrava com seus amigos e eles comiam boa comida e riam juntos. Havia os maravilhosos momentos em que estava com sua querida esposa e podia desfrutar de seus afetos. E, ah, havia o inestimável prazer de brincar e contar histórias para seus filhos. Ora, todos esses são prazeres e alegrias reais e, em certo sentido, davam razão à sua vida. 
Contudo, é claro que isso não era suficiente para ele. Caso sua vida se resumisse a esses prazeres, ele rapidamente ficaria entediado. Esse era o tipo de homem que era. Ele se matava de trabalhar por isso. Não tanto pelo dinheiro ou pelo sucesso por si mesmos (ainda que apreciasse muito ambos), porém sim porque era incapaz de não trabalhar. E não somente isso, mas era incapaz de não dar tudo de si no trabalho. Irônico como seu cansaço era causado por ele mesmo fazendo mais do que o necessário. 
De repente, começou a trovoar e houve um repentino silêncio na taverna, o que causou um constrangimento coletivo. Logo todos se acostumaram e prosseguiram seus assuntos. Ele, porém, esticou suas pernas e prosseguiu nas divagações. “Valia a pena dar tudo de si?”, era a pergunta que martelava em sua cabeça. A única resposta que conseguia encontrar era “se eu não fizer isso, o que eu faria?”. Ora, ele sabia que responder uma pergunta com outra não era muito de uma resposta, mas todos os outros pensamentos e ideias haviam desaparecido de seu cérebro. 
Enquanto pensava de novo e de novo nessas perguntas, adormeceu...
""".replace("\n", "")
